### PR TITLE
Fixes ldata array usage

### PR DESCRIPTION
**Pull request by arall**

### CODE REVIEW

**Comment by PaulSec** [comment]
Hey there! 
Did you just replace the location of the array usage?

**Comment by arall** [comment]
No, its just that at line 76 you're assuming that `ldata` is an array, which is not if the account was not found.

**Comment by PaulSec** [comment]
Ok but why moving the `ldata[0]` to line 81, isn't it going to produce an error as well?

**Comment by arall** [comment]
Not for me. The error happened to me without this little fix. Try to check an email that doesn't exist on Facebook.

**Pull request closed without merging**
